# 1. Usar a imagem oficial da Microsoft para Azure Functions com Node.js
FROM mcr.microsoft.com/azure-functions/node:4-node18

# 2. Definir o diretório de trabalho dentro do container
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

WORKDIR /home/site/wwwroot

# 3. Copiar os arquivos de dependências (package.json)
COPY package*.json ./

# 4. Instalar as dependências (como tedious ou mssql se for usar banco)
RUN npm install

# 5. Copiar o restante do código da função (inclusive a pasta da função de aluguel)
COPY . .

# O container da Azure Function roda por padrão na porta 80
EXPOSE 80